[package]
name = "fastrmail-imap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "IMAP4rev2 server for FastrMail"

[dependencies]
fastrmail-core = { path = "../fastrmail-core" }
fastrmail-store = { path = "../fastrmail-store" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
anyhow = "1"
