[package]
name = "fastrmail-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "DKIM/SPF/DMARC/ARC + User Auth (JWT/OAuth) for FastrMail"

[dependencies]
fastrmail-core = { path = "../fastrmail-core" }
mail-auth = { version = "0.4", features = ["generate"] }
mail-parser = "0.9"
mail-builder = "0.3"
hickory-resolver = "0.24"
tokio = { version = "1", features = ["full"] }
argon2 = "0.5"
serde = { version = "1", features = ["derive"] }
ldap3 = { version = "0.11", default-features = false, features = ["tls-rustls"] }
anyhow = "1"
tracing = "0.1"
